arch: resnet50
cfg_base: cfg.yaml
cfg_dir: cfgs
dataset_dir: data/raw
embed_dim: 64
epochs: 10
img_size: 224
lr: 0.01
lr_decay: 0.75
lr_gamma: 0.001
margin: 0.2
num_workers: 24
optimizer: adam
out: output
pretrained: dino
resume: ''
rng_seed: 42
sampler: MPerClassSampler
scheduler: lambda
train_batch: 128
type_of_triplets: all
val_batch: 32
weight_decay: 0.0
width_crop: 0
